### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pedroalbanese** [JojiiOfficial/shred#1]
Hi,

Does it make a difference to reverse the order of functions? Example:

shredconf := shred.NewShredderConf(&shredder, shred.WriteZeros|shred.WriteRand, 25, true)

What does 1 refer to? Just writing randomly or writing with zeros too? It is the number of iterations of which of the functions? Or both?

Thanks in advance.

**Comment by JojiiOfficial** [comment]
Nope the order doesn't change anything. The order is always WriteRand -> WriteZeros. The ShredderConf you provided writes random bytes and then Zeros, both 25 times.

**Comment by pedroalbanese** [comment]
Is it possible to reverse the order?
I am implementing the "Data Sanitization Method GOST R 50739-95" which is just the opposite..

**Comment by JojiiOfficial** [comment]
You can change the order of the function calls [here](https://github.com/JojiiOfficial/shred/blob/master/shred.go#L102).

**Comment by pedroalbanese** [comment]
It works! Thank You !!
